[package]
authors = ["Alexandre Bury <alexandre.bury@gmail.com>"]
build = "build.rs"
categories = [
    "api-bindings",
    "compression",
]
description = "Low-level bindings for the zstd compression library."
keywords = [
    "zstd",
    "zstandard",
    "compression",
]
license = "MIT/Apache-2.0"
links = "zstd"
name = "zstd-sys"
readme = "Readme.md"
repository = "https://github.com/gyscos/zstd-rs"
version = "1.4.15+zstd.1.4.4"

[build-dependencies]
glob = "0.3"
itertools = "0.8.1"

[build-dependencies.bindgen]
optional = true
version = "0.53.1"

[build-dependencies.pkg-config]
optional = true
version = "0.3"

[build-dependencies.cc]
version = "1.0.45"
features = ["parallel"]

[dependencies]
libc = "0.2.45"

[features]
default = ["legacy"]
non-cargo = [] # Silence cargo-specific build flags
legacy = [] # Enable legacy ZSTD support (for versions < zstd-0.8)
zstdmt = [] # Enable multi-thread support (with pthread)
experimental = [] # Expose experimental ZSTD API
std = [] # Use std types instead of libc in bindgen
