[package]
authors = ["Alexandre Bury <alexandre.bury@gmail.com>"]
description = "Binding for the zstd compression library."
documentation = "https://docs.rs/zstd"
keywords = ["zstd", "zstandard", "compression"]
categories = ["compression", "api-bindings"]
license = "MIT"
name = "zstd"
repository = "https://github.com/gyscos/zstd-rs"
version = "0.7.0+zstd.1.4.9"
exclude = ["assets/*.zst"]
readme = "Readme.md"
edition = "2018"

[package.metadata.docs.rs]
features = ["experimental"]

[badges]
travis-ci = { repository = "gyscos/zstd-rs" }

[dependencies]
zstd-safe = { path = "./zstd-safe", version = "=3.1.0", default-features = false, features=["std"]}
tokio-io = { version = "0.1", optional = true }
futures = { version = "0.1", optional = true }

[dev-dependencies]
clap = "2.0"
partial-io = { version = "0.3", features=["quickcheck", "tokio"] }
quickcheck = "0.6"
humansize = "1.0"
walkdir = "2.2"

[features]
default = ["legacy"]
tokio = ["tokio-io", "futures"]

bindgen = ["zstd-safe/bindgen"]
debug = ["zstd-safe/debug"]
legacy = ["zstd-safe/legacy"]
pkg-config = ["zstd-safe/pkg-config"]
wasm = []
zstdmt = ["zstd-safe/zstdmt"]
experimental = ["zstd-safe/experimental"]
thin = ["zstd-safe/thin"]
